/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_user (void);
GtkWidget* create_gestion_des_utilisateurs (void);
GtkWidget* create_modifier_user (void);
GtkWidget* create_detection (void);
GtkWidget* create_login_window (void);
